repos:
  - repo: https://github.com/prettier/prettier
    rev: "2.0.5"
    hooks:
      - id: prettier
  - repo: https://github.com/lovesegfault/beautysh
    rev: "6.0.1"
    hooks:
      - id: beautysh
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: "2.1.0"
    hooks:
      - id: shellcheck
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: "v2.0.0"
    hooks:
      - id: docker-compose-check
      - id: hadolint
