# x11docker/mate
FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04

ARG DEBIAN_FRONTEND
ENV SHELL /bin/bash
ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

# Copy scripts
COPY scripts scripts

# Setup apt-get
RUN apt-get update

# Common Dependencies
RUN ./scripts/common_dependencies.sh

# Language/locale settings
RUN echo $LANG UTF-8 > /etc/locale.gen && \
    apt-get install -y \
      locales && \
    update-locale --reset LANG=$LANG

# Mate desktop
RUN ./scripts/mate_desktop.sh

# Install docker and docker-compose
RUN ./scripts/docker_install.sh

# Install Extra Apps
RUN ./scripts/extra_apps.sh

# Install communication (Signal, Skype, Slack, Zoom)
# RUN ./scripts/communication_install.sh

# Install pycharm
RUN ./scripts/pycharm_install.sh
COPY jetbrains-pycharm-ce.desktop /usr/share/applications/jetbrains-pycharm-ce.desktop

# Install Visual Studio Code
RUN ./scripts/vs_code_install.sh

# Install Developement Helpers
RUN ./scripts/development_helpers.sh
COPY ./postman.desktop /usr/share/applications/postman.desktop

############################################################
# Other settings
############################################################ 

# Disable "Super-L" keybinding for locking screen in container. 
# It screws up the keyboard
RUN gsettings set org.mate.Marco.global-keybindings run-command-1 ''

CMD ["mate-session"]
