FROM linuxserver/webtop:ubuntu-mate

ARG DEBIAN_FRONTEND
ENV SHELL /bin/bash
ENV LANG en_US.UTF-8
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

# Setup apt-get
RUN apt-get update

# Common Dependencies
COPY scripts/common_dependencies.sh scripts/common_dependencies.sh
RUN ./scripts/common_dependencies.sh

# Language/locale settings
RUN echo $LANG UTF-8 > /etc/locale.gen && \
    apt-get install -y \
      locales && \
    update-locale --reset LANG=$LANG

# Install docker and docker-compose
COPY scripts/docker_install.sh scripts/docker_install.sh
RUN ./scripts/docker_install.sh

# Install Extra Apps
COPY scripts/extra_apps.sh scripts/extra_apps.sh
RUN ./scripts/extra_apps.sh

# Install pycharm
COPY scripts/pycharm_install.sh scripts/pycharm_install.sh
RUN ./scripts/pycharm_install.sh
COPY jetbrains-pycharm-ce.desktop /usr/share/applications/jetbrains-pycharm-ce.desktop

# Install Visual Studio Code
COPY scripts/vs_code_install.sh scripts/vs_code_install.sh
RUN ./scripts/vs_code_install.sh

# Install Development Helpers
COPY scripts/development_helpers.sh scripts/development_helpers.sh
RUN ./scripts/development_helpers.sh
COPY ./postman.desktop /usr/share/applications/postman.desktop

# Copy over mysql helper script
COPY scripts/mysql_start.sh scripts/mysql_start.sh
